### ISSUE TITLE
Support VS Code 1.44.0 (March 2020 Release)

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#92]
- [x] Workbench.executeCommand() appears to be broken #90
- [x] .suggest-widget error with VS Code 1.44.0 #93
- [x] Notification message are no more found with VS Code 1.44.0 #95

**Comment by apupier** [comment]
created PR to have job launching test with 1.44.0 version. There are 29 failing tests: https://travis-ci.com/github/redhat-developer/vscode-extension-tester/jobs/318062241#L509

**Comment by apupier** [comment]
fixed in 2.6.0
